name: Docker Image Release

on:
  push:
    branches: [ master ]

jobs:
  
  build_latest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.1.0
      with:
        owner: tensorflow
        repo: serving
    - name: Show latest release
      env:
        LATEST: ${{ steps.latest_version.outputs.latest_tag }}
        LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
      run: |
        echo "Version $LATEST was released at $LATEST_DATE"
